version: latest

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    hostname: sqlserver
    volumes:
      - mssql_data:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Ig9379992"
    ports:
      - "1455:1433"
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
  timetracker:
    build:
      context: .
      dockerfile: ./TimeTracker/Dockerfile
    depends_on:
      - sqlserver
    container_name: timetracker_api
    image: timetracker
    ports:
      - "8080:80"
    environment:
      - BD_HOST=sqlserver
      - DB_NAME=NewPropperTimeTracker
      - DB_SA_PASSWORD=Ig9379992
  notification:
    build:
      context: .
      dockerfile: ./Notification.Host/Dockerfile
    ports:
      - "9090:80"    

volumes:
  mssql_data: {}      