version: latest

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    hostname: sqlserver
    volumes:
      - mssql_data:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Ig9379992"
    ports:
      - "1455:1433"

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  timetracker:
    build:
      context: .
      dockerfile: Dockerfile.API
    depends_on:
      sqlserver:
        condition: "service_started"
    container_name: timetracker_api
    image: timetracker_api
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"

  notification:
    build:
      context: .
      dockerfile: Dockerfile.Service
    container_name: notification_service
    image: notification_service
    ports:
      - "9090:80"    

volumes:
  mssql_data: {}      