version: latest

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    hostname: sqlserver
    volumes:
      - mssql_data:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Ig9379992"
    ports:
      - "1455:1433"
  timetracker:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - sqlserver
    container_name: timetracker_api
    image: timetracker
    ports:
      - "8080:80"
  backgroundservice:
    build:
      context: .
      dockerfile: ../BackgroundService/Dockerfile
    depends_on:
      - sqlserver
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbit
    ports:
     - "5672:5672"
     - "15672:15672"

volumes:
  mssql_data: {}