version: '3.8'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    hostname: sqlserver
    volumes:
      - mssql_data:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Ig9379992"
    ports:
      - "1455:1433"
  timetracker:
    build: .
    depends_on:
      - sqlserver
    container_name: timetracker_api
    image: timetracker
    ports:
      - "8080:80"

volumes:
  mssql_data: {}